name: Deploy to cloudtype

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: dev.jinsung1017/pawalert
          stage: main
          yaml: |
            name: pawalertbackendteamgroup
            app: java@17
            options:
              ports: 8080
              env:
                - name: SPRING_DATASOURCE_URL
                  value: ${{ secrets.DB_URL }}
                - name: SPRING_DATASOURCE_USERNAME
                  value: ${{ secrets.DB_USER }}
                - name: SPRING_DATASOURCE_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
                  value: ${{ secrets.GOOGLE_CLIENT_ID }}
                - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
                  value: ${{ secrets.GOOGLE_CLIENT_SECRET }}
                - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID
                  value: ${{ secrets.NAVER_CLIENT_ID }}
                - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET
                  value: ${{ secrets.NAVER_CLIENT_SECRET }}
                - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID
                  value: ${{ secrets.KAKAO_CLIENT_ID }}
                - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET
                  value: ${{ secrets.KAKAO_CLIENT_SECRET }}
                - name: JWT_SECRET
                  value: ${{ secrets.JWT_SECRET }}
                - name: SPRING_DATA_MONGODB_USERNAME
                  value: ${{ secrets.MONGO_USERNAME }}
                - name: SPRING_DATA_MONGODB_DATABASE
                  value: ${{ secrets.MONGO_DATABASE }}
                - name: SPRING_DATA_MONGODB_PASSWORD
                  value: ${{ secrets.MONGO_PASSWORD }}
                # AWS 관련 환경 변수 추가
                - name: SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY
                  value: ${{ secrets.AWS_ACCESS_KEY }}
                - name: SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY
                  value: ${{ secrets.AWS_SECRET_KEY }}
                - name: SPRING_CLOUD_AWS_S3_BUCKET
                  value: ${{ secrets.SPRING_CLOUD_AWS_S3_BUCKET }}
                - name: SPRING_CLOUD_AWS_S3_PUBLIC_FOLDER
                 value: ${{ secrets.SPRING_CLOUD_AWS_S3_PUBLIC_FOLDER }}
                - name: SPRING_CLOUD_AWS_S3_PRIVATE_FOLDER
                  value: ${{ secrets.SPRING_CLOUD_AWS_S3_PRIVATE_FOLDER }}
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
